/**
 * lib/missions/templates.ts
 * Mission Template Catalog (22 templates)
 * Brief 10 Implementation
 *
 * Defines all mission templates with steps, credits, and metadata
 */

import { MissionTemplate } from "./types";

// ============================================================================
// TEMPLATE REGISTRY
// ============================================================================

export const MISSION_TEMPLATES: Record<string, MissionTemplate> = {
  // ========================================================================
  // EXECUTION MISSIONS (Content Generation)
  // ========================================================================

  content_batch_3d: {
    template_code: "content_batch_3d",
    name: "Quick Content Batch (3 days)",
    description: "Generate 3 content pieces for 3-day sprint",
    type: "execution",
    phase_min: "F0",
    phase_max: "F7",
    credit_cost_premium: 50,
    credit_cost_allowance: 80,
    estimated_minutes: 45,
    cooldown_hours: 72,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Content Hooks",
        config: { prompt_id: "content_hooks_3d", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 50,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Content Pieces",
        config: { output_type: "content_batch" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "user_input",
        name: "User Review & Approval",
        config: { user_prompt: "Review and approve generated content" },
        timeout_seconds: 259200, // 72h
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        content_count: { type: "number", minimum: 1, maximum: 10 },
        tone: { type: "string", enum: ["professional", "casual", "humorous"] },
      },
      required: ["content_count"],
    },
    generation_intents: ["content_hooks", "content_guiones"],
    expected_artifacts: ["text_content"],
    human_gates: ["content_approval"],
    cost_profile: "S",
  },

  content_batch_7d: {
    template_code: "content_batch_7d",
    name: "Medium Content Batch (7 days)",
    description: "Generate 7 content pieces for weekly plan",
    type: "execution",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 200,
    credit_cost_allowance: 140,
    estimated_minutes: 90,
    cooldown_hours: 168,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Content Hooks (7x)",
        config: { prompt_id: "content_hooks_7d", model_preference: "gpt-4" },
        timeout_seconds: 60,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 100,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Content Pieces",
        config: { output_type: "content_batch" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "user_input",
        name: "User Review & Approval",
        config: { user_prompt: "Review and approve 7-day content plan" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        content_count: { type: "number", minimum: 5, maximum: 20 },
        tone: { type: "string" },
      },
      required: ["content_count"],
    },
    generation_intents: ["content_hooks", "content_guiones"],
    expected_artifacts: ["text_content"],
    human_gates: ["content_approval"],
    cost_profile: "M",
  },

  content_batch_14d: {
    template_code: "content_batch_14d",
    name: "Large Content Batch (14 days)",
    description: "Generate 14 content pieces for biweekly plan",
    type: "execution",
    phase_min: "F2",
    phase_max: "F7",
    credit_cost_premium: 400,
    credit_cost_allowance: 250,
    estimated_minutes: 180,
    cooldown_hours: 336,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Content Hooks (14x)",
        config: { prompt_id: "content_hooks_14d", model_preference: "gpt-4" },
        timeout_seconds: 120,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 200,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Content Pieces",
        config: { output_type: "content_batch" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "user_input",
        name: "User Review & Approval",
        config: { user_prompt: "Review and approve 14-day content plan" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        content_count: { type: "number", minimum: 10, maximum: 30 },
      },
    },
    generation_intents: ["content_hooks", "content_guiones"],
    expected_artifacts: ["text_content"],
    human_gates: ["content_approval"],
    cost_profile: "L",
  },

  image_gen_batch: {
    template_code: "image_gen_batch",
    name: "Generate Image Batch",
    description: "Generate images for content pieces",
    type: "execution",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 50,
    credit_cost_allowance: 0,
    estimated_minutes: 60,
    cooldown_hours: 24,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "premium_action",
        name: "Generate Images",
        config: { action_type: "image_generation", model: "dalle-3" },
        timeout_seconds: 300,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "premium",
        credit_amount: 40,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Assets",
        config: { output_type: "image_assets" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "user_input",
        name: "User Review",
        config: { user_prompt: "Review generated images" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        image_count: { type: "number", minimum: 1, maximum: 20 },
        style: { type: "string" },
      },
      required: ["image_count"],
    },
    generation_intents: ["images"],
    expected_artifacts: ["image"],
    human_gates: ["image_approval"],
    cost_profile: "M",
  },

  // ========================================================================
  // DISCOVERY MISSIONS (Scraping & Analysis)
  // ========================================================================

  scrape_light_focus: {
    template_code: "scrape_light_focus",
    name: "Light Scrape (Focus)",
    description: "Quick scrape of recent account data",
    type: "discovery",
    phase_min: "F0",
    phase_max: "F7",
    credit_cost_premium: 5,
    credit_cost_allowance: 0,
    estimated_minutes: 15,
    cooldown_hours: 24,
    steps_json: [
      {
        step_number: 1,
        step_type: "premium_action",
        name: "Scrape Account",
        config: {
          action_type: "scrape",
          platform: "instagram",
          depth: "light",
        },
        timeout_seconds: 60,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "premium",
        credit_amount: 5,
      },
      {
        step_number: 2,
        step_type: "brain_update",
        name: "Update Brain Signals",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 3,
        step_type: "snapshot",
        name: "Create Brain Snapshot",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        platform: { type: "string", enum: ["instagram", "tiktok", "youtube"] },
      },
      required: ["platform"],
    },
    generation_intents: ["account_metrics"],
    expected_artifacts: [],
    human_gates: [],
    cost_profile: "S",
  },

  scrape_full_multi: {
    template_code: "scrape_full_multi",
    name: "Full Multi-Platform Scrape",
    description: "Deep scrape across multiple platforms",
    type: "discovery",
    phase_min: "F0",
    phase_max: "F7",
    credit_cost_premium: 25,
    credit_cost_allowance: 0,
    estimated_minutes: 120,
    cooldown_hours: 168,
    steps_json: [
      {
        step_number: 1,
        step_type: "premium_action",
        name: "Scrape All Platforms",
        config: { action_type: "scrape", depth: "full", multi_platform: true },
        timeout_seconds: 300,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "premium",
        credit_amount: 20,
      },
      {
        step_number: 2,
        step_type: "brain_update",
        name: "Update Brain Signals",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 3,
        step_type: "snapshot",
        name: "Create Brain Snapshot",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        platforms: { type: "array", items: { type: "string" } },
      },
      required: ["platforms"],
    },
    generation_intents: ["account_metrics", "posts_data"],
    expected_artifacts: [],
    human_gates: [],
    cost_profile: "L",
  },

  // ========================================================================
  // ANALYSIS MISSIONS (Reporting & Insights)
  // ========================================================================

  daily_pulse: {
    template_code: "daily_pulse",
    name: "Daily Pulse",
    description: "Daily light metrics check and update",
    type: "analysis",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 5,
    credit_cost_allowance: 15,
    estimated_minutes: 10,
    cooldown_hours: 24,
    steps_json: [
      {
        step_number: 1,
        step_type: "premium_action",
        name: "Fetch Daily Metrics",
        config: { action_type: "fetch_metrics", frequency: "daily" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: true,
        requires_credit: true,
        credit_type: "premium",
        credit_amount: 5,
      },
      {
        step_number: 2,
        step_type: "brain_update",
        name: "Update Brain Signals",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 3,
        step_type: "snapshot",
        name: "Create Checkpoint",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: { type: "object", properties: {} },
    generation_intents: [],
    expected_artifacts: [],
    human_gates: [],
    cost_profile: "S",
  },

  weekly_review: {
    template_code: "weekly_review",
    name: "Weekly Review",
    description: "Comprehensive weekly performance review",
    type: "analysis",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 40,
    estimated_minutes: 30,
    cooldown_hours: 168,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Weekly Report",
        config: { prompt_id: "weekly_review", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 30,
      },
      {
        step_number: 3,
        step_type: "brain_update",
        name: "Update Brain",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "snapshot",
        name: "Create Snapshot",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: { type: "object", properties: {} },
    generation_intents: ["weekly_report"],
    expected_artifacts: ["text_content"],
    human_gates: [],
    cost_profile: "M",
  },

  // ========================================================================
  // PLANNING MISSIONS (Strategy & Optimization)
  // ========================================================================

  strategy_recalc: {
    template_code: "strategy_recalc",
    name: "Strategy Recalculation",
    description: "Recalculate overall strategy based on signals",
    type: "planning",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 50,
    estimated_minutes: 45,
    cooldown_hours: 336,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Strategy",
        config: { prompt_id: "strategy_gen", model_preference: "gpt-4" },
        timeout_seconds: 60,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 40,
      },
      {
        step_number: 3,
        step_type: "brain_update",
        name: "Update Brain",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "snapshot",
        name: "Create Snapshot",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: { type: "object", properties: {} },
    generation_intents: ["strategy_plan"],
    expected_artifacts: [],
    human_gates: [],
    cost_profile: "M",
  },

  // ========================================================================
  // UTILITY MISSIONS
  // ========================================================================

  ask_glimy_chat: {
    template_code: "ask_glimy_chat",
    name: "Ask Glimy (Chat)",
    description: "Quick question to AI assistant",
    type: "discovery",
    phase_min: "F0",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 1,
    estimated_minutes: 2,
    cooldown_hours: 0,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 5,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Process Question",
        config: { prompt_id: "chat_qa", model_preference: "gpt-3.5-turbo" },
        timeout_seconds: 20,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 1,
      },
      {
        step_number: 3,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 5,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        question: { type: "string", minLength: 1, maxLength: 500 },
      },
      required: ["question"],
    },
    generation_intents: [],
    expected_artifacts: [],
    human_gates: [],
    cost_profile: "S",
  },

  repurpose_cross: {
    template_code: "repurpose_cross",
    name: "Repurpose to Multiple Formats",
    description: "Convert single piece to multiple formats",
    type: "execution",
    phase_min: "F2",
    phase_max: "F7",
    credit_cost_premium: 10,
    credit_cost_allowance: 30,
    estimated_minutes: 20,
    cooldown_hours: 24,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Repurposed Content",
        config: { prompt_id: "repurpose", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 20,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Outputs",
        config: { output_type: "repurposed_content" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "user_input",
        name: "User Review",
        config: { user_prompt: "Review repurposed content" },
        timeout_seconds: 86400,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        source_output_id: { type: "string" },
        target_formats: { type: "array", items: { type: "string" } },
      },
      required: ["source_output_id", "target_formats"],
    },
    generation_intents: ["repurposed_content"],
    expected_artifacts: ["text_content"],
    human_gates: ["content_approval"],
    cost_profile: "S",
  },

  autopost_schedule: {
    template_code: "autopost_schedule",
    name: "Auto-Post Scheduler",
    description: "Schedule content for automatic posting",
    type: "execution",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 0,
    estimated_minutes: 10,
    cooldown_hours: 0,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "write_outputs",
        name: "Create Schedule",
        config: { output_type: "post_schedule" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 3,
        step_type: "external_webhook",
        name: "Dispatch to Scheduler",
        config: { webhook_service: "n8n_scheduler" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        output_ids: { type: "array", items: { type: "string" } },
        schedule_config: { type: "object" },
      },
      required: ["output_ids"],
    },
    generation_intents: [],
    expected_artifacts: [],
    human_gates: [],
    cost_profile: "S",
  },

  metrics_post_publish: {
    template_code: "metrics_post_publish",
    name: "Post-Publish Metrics",
    description: "Fetch metrics after content publishing",
    type: "analysis",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 5,
    credit_cost_allowance: 0,
    estimated_minutes: 5,
    cooldown_hours: 2,
    steps_json: [
      {
        step_number: 1,
        step_type: "premium_action",
        name: "Fetch Post Metrics",
        config: { action_type: "fetch_post_metrics" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "premium",
        credit_amount: 5,
      },
      {
        step_number: 2,
        step_type: "brain_update",
        name: "Update Brain",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 3,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        post_id: { type: "string" },
      },
      required: ["post_id"],
    },
    generation_intents: [],
    expected_artifacts: [],
    human_gates: [],
    cost_profile: "S",
  },

  // ========================================================================
  // ANALYSIS MISSIONS (Format Audit)
  // ========================================================================

  format_audit: {
    template_code: "format_audit",
    name: "Format Audit",
    description: "Analyze current content formats and recommend optimal mix",
    type: "analysis",
    phase_min: "F0",
    phase_max: "F3",
    credit_cost_premium: 0,
    credit_cost_allowance: 20,
    estimated_minutes: 15,
    cooldown_hours: 168,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Analyze Format Performance",
        config: { prompt_id: "format_audit", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 20,
      },
      {
        step_number: 3,
        step_type: "brain_update",
        name: "Store Format Insights",
        config: { facts: ["format_audit_result"] },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {},
      required: [],
    },
    generation_intents: ["analyze_formats"],
    expected_artifacts: ["format_audit_report"],
    human_gates: [],
    cost_profile: "S",
  },

  // ========================================================================
  // PLANNING MISSIONS
  // ========================================================================

  niche_refinement: {
    template_code: "niche_refinement",
    name: "Niche Refinement",
    description: "Refine and validate the creator's niche and positioning",
    type: "planning",
    phase_min: "F0",
    phase_max: "F2",
    credit_cost_premium: 0,
    credit_cost_allowance: 30,
    estimated_minutes: 20,
    cooldown_hours: 336,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Niche Options",
        config: { prompt_id: "niche_refinement", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 30,
      },
      {
        step_number: 3,
        step_type: "user_input",
        name: "Select Niche",
        config: { user_prompt: "Choose your refined niche from the options" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "brain_update",
        name: "Store Refined Niche",
        config: { facts: ["refined_niche", "niche_rationale"] },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {},
      required: [],
    },
    generation_intents: ["refine_niche"],
    expected_artifacts: ["niche_profile"],
    human_gates: ["niche_selection"],
    cost_profile: "S",
  },

  content_pillar_gen: {
    template_code: "content_pillar_gen",
    name: "Content Pillar Generation",
    description: "Define 3-5 content pillars aligned with brand strategy",
    type: "planning",
    phase_min: "F0",
    phase_max: "F3",
    credit_cost_premium: 0,
    credit_cost_allowance: 25,
    estimated_minutes: 20,
    cooldown_hours: 336,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Content Pillars",
        config: { prompt_id: "content_pillar_gen", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 25,
      },
      {
        step_number: 3,
        step_type: "user_input",
        name: "Approve Pillars",
        config: { user_prompt: "Review and approve your content pillars" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "brain_update",
        name: "Store Content Pillars",
        config: { facts: ["content_pillars"] },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {},
      required: [],
    },
    generation_intents: ["define_pillars"],
    expected_artifacts: ["content_pillars_doc"],
    human_gates: ["pillars_approval"],
    cost_profile: "S",
  },

  video_gen_short: {
    template_code: "video_gen_short",
    name: "Short Video Generation",
    description: "Generate short-form video content (Reels, TikToks, Shorts)",
    type: "execution",
    phase_min: "F2",
    phase_max: "F7",
    credit_cost_premium: 80,
    credit_cost_allowance: 0,
    estimated_minutes: 60,
    cooldown_hours: 24,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "premium_action",
        name: "Generate Video",
        config: { action_type: "video_generation" },
        timeout_seconds: 300,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "premium",
        credit_amount: 80,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Video Output",
        config: { output_type: "video" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "user_input",
        name: "Review Video",
        config: { user_prompt: "Review and approve the generated video" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        duration_seconds: { type: "number", minimum: 15, maximum: 60 },
        platform: { type: "string", enum: ["instagram", "tiktok", "youtube"] },
      },
      required: [],
    },
    generation_intents: ["generate_video"],
    expected_artifacts: ["video_file"],
    human_gates: ["video_approval"],
    cost_profile: "L",
  },

  calendar_optimize: {
    template_code: "calendar_optimize",
    name: "Calendar Optimization",
    description: "Optimize content calendar for maximum engagement timing",
    type: "planning",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 20,
    estimated_minutes: 15,
    cooldown_hours: 168,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Optimize Posting Schedule",
        config: { prompt_id: "calendar_optimize", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 20,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Calendar Plan",
        config: { output_type: "schedule" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        weeks_ahead: { type: "number", minimum: 1, maximum: 4 },
      },
      required: [],
    },
    generation_intents: ["optimize_calendar"],
    expected_artifacts: ["calendar_plan"],
    human_gates: [],
    cost_profile: "S",
  },

  engagement_rescue: {
    template_code: "engagement_rescue",
    name: "Engagement Rescue",
    description: "Emergency strategy when engagement drops significantly",
    type: "rescue",
    phase_min: "F1",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 35,
    estimated_minutes: 30,
    cooldown_hours: 72,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Rescue Plan",
        config: { prompt_id: "engagement_rescue", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 35,
      },
      {
        step_number: 3,
        step_type: "write_outputs",
        name: "Persist Rescue Content",
        config: { output_type: "content" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "user_input",
        name: "Approve Rescue Plan",
        config: {
          user_prompt: "Review and approve the engagement rescue strategy",
        },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {},
      required: [],
    },
    generation_intents: ["rescue_engagement"],
    expected_artifacts: ["rescue_content_batch"],
    human_gates: ["rescue_approval"],
    cost_profile: "M",
  },

  monetize_product_def: {
    template_code: "monetize_product_def",
    name: "Monetization Product Definition",
    description: "Define a digital product concept aligned with audience needs",
    type: "planning",
    phase_min: "F3",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 40,
    estimated_minutes: 30,
    cooldown_hours: 336,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Define Product Concept",
        config: {
          prompt_id: "monetize_product_def",
          model_preference: "gpt-4",
        },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 40,
      },
      {
        step_number: 3,
        step_type: "user_input",
        name: "Validate Product Idea",
        config: { user_prompt: "Review and validate the product concept" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "brain_update",
        name: "Store Product Definition",
        config: { facts: ["product_definition"] },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {},
      required: [],
    },
    generation_intents: ["define_product"],
    expected_artifacts: ["product_brief"],
    human_gates: ["product_validation"],
    cost_profile: "M",
  },

  monetize_offer_build: {
    template_code: "monetize_offer_build",
    name: "Monetization Offer Builder",
    description:
      "Build a complete sales offer with pricing and landing content",
    type: "execution",
    phase_min: "F4",
    phase_max: "F7",
    credit_cost_premium: 30,
    credit_cost_allowance: 60,
    estimated_minutes: 60,
    cooldown_hours: 168,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Generate Offer Copy",
        config: {
          prompt_id: "monetize_offer_build",
          model_preference: "gpt-4",
        },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 60,
      },
      {
        step_number: 3,
        step_type: "premium_action",
        name: "Generate Offer Visuals",
        config: { action_type: "image_generation" },
        timeout_seconds: 120,
        retry_max: 2,
        skip_on_failure: true,
        requires_credit: true,
        credit_type: "premium",
        credit_amount: 30,
      },
      {
        step_number: 4,
        step_type: "write_outputs",
        name: "Persist Offer Assets",
        config: { output_type: "content" },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 5,
        step_type: "user_input",
        name: "Approve Offer",
        config: { user_prompt: "Review and approve the offer package" },
        timeout_seconds: 259200,
        retry_max: 0,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 6,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {
        product_name: { type: "string" },
        price_usd: { type: "number", minimum: 1 },
      },
      required: [],
    },
    generation_intents: ["build_offer"],
    expected_artifacts: ["offer_copy", "offer_visuals"],
    human_gates: ["offer_approval"],
    cost_profile: "L",
  },

  audience_deep_dive: {
    template_code: "audience_deep_dive",
    name: "Audience Deep Dive",
    description:
      "Deep analysis of audience demographics, behavior, and preferences",
    type: "analysis",
    phase_min: "F2",
    phase_max: "F7",
    credit_cost_premium: 0,
    credit_cost_allowance: 30,
    estimated_minutes: 25,
    cooldown_hours: 168,
    steps_json: [
      {
        step_number: 1,
        step_type: "brain_read",
        name: "Read Brain Context",
        config: {},
        timeout_seconds: 10,
        retry_max: 3,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 2,
        step_type: "llm_text",
        name: "Analyze Audience Profile",
        config: { prompt_id: "audience_deep_dive", model_preference: "gpt-4" },
        timeout_seconds: 30,
        retry_max: 2,
        skip_on_failure: false,
        requires_credit: true,
        credit_type: "allowance",
        credit_amount: 30,
      },
      {
        step_number: 3,
        step_type: "brain_update",
        name: "Store Audience Insights",
        config: { facts: ["audience_profile", "audience_segments"] },
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: true,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
      {
        step_number: 4,
        step_type: "finalize",
        name: "Complete Mission",
        config: {},
        timeout_seconds: 10,
        retry_max: 1,
        skip_on_failure: false,
        requires_credit: false,
        credit_type: null,
        credit_amount: 0,
      },
    ],
    params_schema: {
      type: "object",
      properties: {},
      required: [],
    },
    generation_intents: ["analyze_audience"],
    expected_artifacts: ["audience_report"],
    human_gates: [],
    cost_profile: "S",
  },
};

// ============================================================================
// TEMPLATE REGISTRY FUNCTIONS
// ============================================================================

export function getTemplate(templateCode: string): MissionTemplate | null {
  return MISSION_TEMPLATES[templateCode] || null;
}

export function listTemplates(
  filterType?: string,
  filterPhase?: string,
): MissionTemplate[] {
  return Object.values(MISSION_TEMPLATES).filter((t) => {
    if (filterType && t.type !== filterType) return false;
    if (filterPhase) {
      if (t.phase_min && filterPhase < t.phase_min) return false;
      if (t.phase_max && filterPhase > t.phase_max) return false;
    }
    return true;
  });
}

export function getTemplatesByType(type: string): MissionTemplate[] {
  return Object.values(MISSION_TEMPLATES).filter((t) => t.type === type);
}

export function calculateTotalCost(
  templateCode: string,
): { allowance: number; premium: number } | null {
  const template = getTemplate(templateCode);
  if (!template) return null;

  return {
    allowance: template.credit_cost_allowance,
    premium: template.credit_cost_premium,
  };
}
